### ISSUE TITLE
Greek characters and `\ ` are not handled

### ISSUE THREAD

**Issue by Blaisorblade** [inukshuk/latex-decode#8]
Hi! Thanks for this library! We are using it together with bibtex-ruby, but my colleague @Toxaris needed to add some extensions, and I thought that long-term they might belong in your library.

In particular:

- Greek letters aren't translated to Unicode
- `\ ` is only handled after a command, even though [it also makes sense after e.g. a dot](http://tex.stackexchange.com/a/2236/1340) (and is correct anywhere IIUC).

See [discussion](https://github.com/ps-mr/website/issues/19#issuecomment-72359381) and commits (ps-mr/website@6caefa25989bd672d632db875af530a2e365c1e0, 
ps-mr/website@5e4aff9625664ce9633e4a66db286869110f5d7d).

**Comment by inukshuk** [comment]
Awesome! Could you turn this into a PR?

I would put the Greek letters into a separate file (i.e., lib/latex/decode/greek.rb) and add a feature file to features/greek.feature (I just updated the Travis-CI config to make sure the tests still work).

**Comment by Blaisorblade** [comment]
From my POV, right now, it might be faster if you fetched the code, if that's OK, unless the code author @Toxaris volunteers to submit the PR — I'm not a good *Ruby* developer. (I might get to it eventually). I hope that's not impolite or something.

**Comment by Blaisorblade** [comment]
Ahem, of course we should clear the matter of the license for that we don't have any license right now on the code, but I'm guessing we're fine with BSD-licensing this code (the content of the website is a different matter, no idea there).

**Comment by inukshuk** [comment]
latex-decode is licensed under the GPL. If you're happy with this, I can push this to Rubygems, so you don't have to patch the Gem on your end.

**Comment by Blaisorblade** [comment]
I guess GPL would also not be a problem, if nothing else because BSD is GPL-compatible. But I'll just need to actually talk to @Toxaris, if he doesn't confirm himself, since he wrote that code.

**Comment by Toxaris** [comment]
I'm happy with a GPL license for this contribution to latex-decode. Thanks Blaisorblade and inukshuk for taking care that the code gets merged here!

**Comment by inukshuk** [comment]
Landed in 0.2.0

**Comment by Blaisorblade** [comment]
Thanks a lot!
